#!/bin/bash

# if there's a docker-sync folder we assume that
# the docker-sync configuration should be used
if [ -d ".docker-sync" ]
then
    docker-compose -f docker-compose.yml -f docker-compose-sync.yml "$@"
else
    docker-compose "$@"
fi