services:

  apache:
    image: totara/docker-dev-apache
    container_name: totara_apache
    restart: ${RESTART_POLICY:-no}
    environment:
      - TZ=${TIME_ZONE}
      - REMOTE_DATA
      - REMOTE_SRC
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443" # ngrok only
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
    depends_on:
      - maildev
    networks:
      - totara

volumes:
  totara-data: