services:

  apache:
    image: totara/docker-dev-apache
    container_name: totara_apache
    environment:
      - TZ=${TIME_ZONE}
      - REMOTE_DATA
      - REMOTE_SRC
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443" # ngrok only
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
    depends_on:
      - mailcatcher
    networks:
      totara:
        aliases:
          - totara54
          - totara54.debug
          - totara54.behat
          - totara54.behat.totaralms.com
          - totara55
          - totara55.debug
          - totara55.behat
          - totara55.behat.totaralms.com
          - totara56
          - totara56.debug
          - totara56.behat
          - totara56.behat.totaralms.com
          - totara70
          - totara70.debug
          - totara70.behat
          - totara70.behat.totaralms.com
          - totara71
          - totara71.debug
          - totara71.behat
          - totara71.behat.totaralms.com
          - totara72
          - totara72.debug
          - totara72.behat
          - totara72.behat.totaralms.com
          - totara73
          - totara73.debug
          - totara73.behat
          - totara73.behat.totaralms.com
          - totara74
          - totara74.debug
          - totara74.behat
          - totara74.behat.totaralms.com
          - totara80
          - totara80.behat
          - totara80.behat.totaralms.com
          - totara81
          - totara81.behat
          - totara81.behat.totaralms.com
          - totara82
          - totara82.behat
          - totara82.behat.totaralms.com
          - totara83
          - totara83.behat
          - totara83.behat.totaralms.com

volumes:
  totara-data: