services:

  apache:
    build: ./apache

  nginx:
    build: ./nginx

  mssql2017:
    build:
      context: ./mssql
      dockerfile: 2017/Dockerfile

  mssql2019:
    build:
      context: ./mssql
      dockerfile: 2019/Dockerfile

  mssql2022:
    build:
      context: ./mssql
      dockerfile: 2022/Dockerfile

  php-7.3:
    build:
      context: ./php
      dockerfile: php73/Dockerfile
      args:
        TIME_ZONE: ${TIME_ZONE}

  php-7.4:
    build:
      context: ./php
      dockerfile: php74/Dockerfile
      args:
        TIME_ZONE: ${TIME_ZONE}

  php-8.0:
    build:
      context: ./php
      dockerfile: php80/Dockerfile
      args:
        TIME_ZONE: ${TIME_ZONE}

  php-8.1:
    build:
      context: ./php
      dockerfile: php81/Dockerfile
      args:
        TIME_ZONE: ${TIME_ZONE}

  php-8.2:
    build:
      context: ./php
      dockerfile: php82/Dockerfile
      args:
        TIME_ZONE: ${TIME_ZONE}

  php-8.3:
    build:
      context: ./php
      dockerfile: php83/Dockerfile
      args:
        TIME_ZONE: ${TIME_ZONE}

  php-8.4:
    build:
      context: ./php
      dockerfile: php84/Dockerfile
      args:
        TIME_ZONE: ${TIME_ZONE}

  # php-X.X: ...
