version: "3.7"
services:

  mariadb:
    image: mariadb:10.5
    container_name: totara_mariadb105
    ports:
      - "3307:3306"
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb:/etc/mysql/conf.d
    depends_on:
      - nginx
    networks:
      - totara

  mariadb104:
    image: mariadb:10.4
    container_name: totara_mariadb104
    ports:
      - "3309:3306"
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mariadb104-data:/var/lib/mysql
      - ./mariadb:/etc/mysql/conf.d
    depends_on:
      - nginx
    networks:
      - totara

  mariadb102:
    image: mariadb:10.2
    container_name: totara_mariadb102
    ports:
      - "3302:3306"
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    volumes:
      - mariadb102-data:/var/lib/mysql
      - ./mariadb:/etc/mysql/conf.d
    depends_on:
      - nginx
    networks:
      - totara

volumes:
  mariadb-data:
  mariadb104-data:
  mariadb102-data:
