x-healthcheck-template: &mssql-healthcheck
  healthcheck:
    test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S 127.0.0.1 -U sa -P $$MSSQL_SA_PASSWORD -Q 'SELECT 1' -C 2>/dev/null"]
    interval: 5s
    timeout: 5s
    retries: 5
    start_period: 30s

x-healthcheck-template-legacy: &mssql-healthcheck-legacy
  healthcheck:
    test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U sa -P $$SA_PASSWORD -Q 'SELECT 1' 2>/dev/null"]
    interval: 5s
    timeout: 5s
    retries: 5
    start_period: 30s

services:

  mssql2017:
    <<: *mssql-healthcheck-legacy
    image: ghcr.io/totara/docker-dev-mssql2017
    # Mssql does not support multiple architectures
    platform: linux/amd64
    container_name: totara_mssql2017
    restart: ${RESTART_POLICY:-no}
    ports:
      - "1433:1433"
    environment:
      TZ: ${TIME_ZONE}
      ACCEPT_EULA: Y
      SA_PASSWORD: ${MSSQL_SA_PW}
      MSSQL_PID: Developer
    volumes:
      - mssql-data:/var/opt/mssql
    depends_on:
      - nginx
    networks:
      - totara

  mssql2019:
    <<: *mssql-healthcheck-legacy
    image: ghcr.io/totara/docker-dev-mssql2019
    # Mssql does not support multiple architectures
    platform: linux/amd64
    container_name: totara_mssql2019
    restart: ${RESTART_POLICY:-no}
    ports:
      - "1419:1433"
    environment:
      TZ: ${TIME_ZONE}
      ACCEPT_EULA: Y
      SA_PASSWORD: ${MSSQL_SA_PW}
      MSSQL_PID: Developer
    volumes:
      - mssql2019-data:/var/opt/mssql
    depends_on:
      - nginx
    networks:
      - totara

  mssql2022:
    <<: *mssql-healthcheck
    image: ghcr.io/totara/docker-dev-mssql2022
    # Mssql does not support multiple architectures
    platform: linux/amd64
    container_name: totara_mssql2022
    restart: ${RESTART_POLICY:-no}
    ports:
      - "1420:1433"
    environment:
      TZ: ${TIME_ZONE}
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PW}
      MSSQL_PID: Developer
    volumes:
      - mssql2022-data:/var/opt/mssql
    depends_on:
      - nginx
    networks:
      - totara

  # When adding a new MSSQL container here, make sure you also:
  # - Add a build entry in compose/build.yml
  # - Add a CI build entry in .github/workflows/build-mssql.yml
  # - Add a image matrix entry in .github/workflows/scan-images.yml
  # - Update README.md

volumes:
  mssql-data:
  mssql2019-data:
  mssql2022-data:
