services:

  mssql2017:
    image: totara/docker-dev-mssql
    # Mssql does not support multiple architectures
    platform: linux/amd64
    container_name: totara_mssql
    restart: ${RESTART_POLICY:-no}
    ports:
      - "1433:1433"
    environment:
      TZ: ${TIME_ZONE}
      ACCEPT_EULA: Y
      SA_PASSWORD: ${MSSQL_SA_PW}
      MSSQL_PID: Developer
    volumes:
      - mssql-data:/var/opt/mssql
    depends_on:
      - nginx
    networks:
      - totara

  mssql2019:
    image: totara/docker-dev-mssql2019
    # Mssql does not support multiple architectures
    platform: linux/amd64
    container_name: totara_mssql2019
    restart: ${RESTART_POLICY:-no}
    ports:
      - "1419:1433"
    environment:
      TZ: ${TIME_ZONE}
      ACCEPT_EULA: Y
      SA_PASSWORD: ${MSSQL_SA_PW}
      MSSQL_PID: Developer
    volumes:
      - mssql2019-data:/var/opt/mssql
    depends_on:
      - nginx
    networks:
      - totara

  mssql2022:
    image: totara/docker-dev-mssql2022
    # Mssql does not support multiple architectures
    platform: linux/amd64
    container_name: totara_mssql2022
    restart: ${RESTART_POLICY:-no}
    ports:
      - "1420:1433"
    environment:
      TZ: ${TIME_ZONE}
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PW}
      MSSQL_PID: Developer
    volumes:
      - mssql2022-data:/var/opt/mssql
    depends_on:
      - nginx
    networks:
      - totara

  # When adding a new MSSQL container, make sure you also add entries in:
  # compose/build.yml, .github/workflows/build-mssql.yml

volumes:
  mssql-data:
  mssql2019-data:
  mssql2022-data:
