version: "3.7"
services:

  mssql:
    image: totara/docker-dev-mssql
    container_name: totara_mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${MSSQL_SA_PW}
      MSSQL_PID: Developer
    volumes:
      - mssql-data:/var/opt/mssql
    depends_on:
      - nginx
    networks:
      - totara

volumes:
  mssql-data:
