version: "3.7"
services:

  mysql8:
    image: mysql:8.0
    container_name: totara_mysql8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    depends_on:
      - nginx
    volumes:
      - mysql80-data:/var/lib/mysql
      - ./mysql8:/etc/mysql/conf.d
    networks:
      - totara

  mysql:
    image: mysql:5.7
    container_name: totara_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    depends_on:
      - nginx
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - totara

volumes:
  mysql-data:
  mysql80-data:
