services:

  mysql8:
    image: mysql:8.0
    container_name: totara_mysql8
    ports:
      - "3308:3306"
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    depends_on:
      - nginx
    volumes:
      - mysql80-data:/var/lib/mysql
      - ./mysql8:/etc/mysql/conf.d
    networks:
      - totara

  mysql57:
    # MySQL 5.7 does not support multiple architectures. (MySQL 8.0 works fine)
    platform: linux/amd64
    image: mysql:5.7
    container_name: totara_mysql57
    ports:
      - "3306:3306"
    environment:
      TZ: ${TIME_ZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
    depends_on:
      - nginx
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - totara

volumes:
  mysql-data:
  mysql80-data:
