version: "2"
services:

  pgsql93:
    image: postgres:9.3
    container_name: totara_pgsql93
    ports:
    - "5493:5432"
    command:
      postgres
      -c max_locks_per_transaction=1024
      -c max_pred_locks_per_transaction=1024
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - pgsql93-data:/var/lib/postgresql/data
    depends_on:
    - nginx
    networks:
    - totara

  pgsql96:
    image: postgres:9.6
    container_name: totara_pgsql96
    ports:
    - "5496:5432"
    command:
      postgres
      -c max_locks_per_transaction=1024
      -c max_pred_locks_per_transaction=1024
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - pgsql96-data:/var/lib/postgresql/data
    depends_on:
    - nginx
    networks:
    - totara

  pgsql10:
    image: postgres:10.6
    container_name: totara_pgsql10
    ports:
    - "5410:5432"
    command:
      postgres
      -c max_locks_per_transaction=1024
      -c max_pred_locks_per_transaction=1024
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - pgsql10-data:/var/lib/postgresql/data
    depends_on:
    - nginx
    networks:
    - totara

  pgsql:
    image: postgres:11.1
    container_name: totara_pgsql11
    ports:
    - "5432:5432"
    command:
      postgres
      -c max_locks_per_transaction=1024
      -c max_pred_locks_per_transaction=1024
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - pgsql11-data:/var/lib/postgresql/data
    depends_on:
    - nginx
    networks:
    - totara

volumes:
  pgsql93-data:
  pgsql96-data:
  pgsql10-data:
  pgsql11-data:

networks:
  totara: