services:

  pgsql93:
    image: postgres:9.3-alpine
    container_name: totara_pgsql93
    ports:
      - "5493:5432"
    environment:
      TZ: ${TIME_ZONE}
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./pgsql/my-postgres.conf:/etc/postgresql/postgresql.conf
      - pgsql93-data:/var/lib/postgresql/data
    depends_on:
      - nginx
    networks:
      - totara

  pgsql96:
    image: postgres:9.6-alpine
    container_name: totara_pgsql96
    ports:
      - "5496:5432"
    environment:
      TZ: ${TIME_ZONE}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./pgsql/my-postgres.conf:/etc/postgresql/postgresql.conf
      - pgsql96-data:/var/lib/postgresql/data
    depends_on:
      - nginx
    networks:
      - totara

  pgsql10:
    image: postgres:10-alpine
    container_name: totara_pgsql10
    ports:
      - "5410:5432"
    environment:
      TZ: ${TIME_ZONE}
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./pgsql/my-postgres.conf:/etc/postgresql/postgresql.conf
      - pgsql10-data:/var/lib/postgresql/data
    depends_on:
      - nginx
    networks:
      - totara

  pgsql11:
    image: postgres:11-alpine
    container_name: totara_pgsql11
    ports:
      - "5411:5432"
    environment:
      TZ: ${TIME_ZONE}
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./pgsql/my-postgres.conf:/etc/postgresql/postgresql.conf
      - pgsql11-data:/var/lib/postgresql/data
    depends_on:
      - nginx
    networks:
      - totara

  pgsql12:
    image: postgres:12-alpine
    container_name: totara_pgsql12
    ports:
      - "5432:5432"
    environment:
      TZ: ${TIME_ZONE}
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./pgsql/my-postgres.conf:/etc/postgresql/postgresql.conf
      - pgsql12-data:/var/lib/postgresql/data
    depends_on:
      - nginx
    networks:
      - totara

  pgsql13:
    image: postgres:13-alpine
    container_name: totara_pgsql13
    ports:
      - "5442:5432"
    environment:
      TZ: ${TIME_ZONE}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./pgsql/my-postgres.conf:/etc/postgresql/postgresql.conf
      - pgsql13-data:/var/lib/postgresql/data
    depends_on:
      - nginx
    networks:
      - totara

  pgsql14:
    image: postgres:14-alpine
    container_name: totara_pgsql14
    ports:
      - "5443:5432"
    environment:
      TZ: ${TIME_ZONE}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      postgres -c 'config_file=/etc/postgresql/postgresql.conf' -c 'enable_memoize=off'
    volumes:
      - ./pgsql/my-postgres.conf:/etc/postgresql/postgresql.conf
      - pgsql14-data:/var/lib/postgresql/data
    depends_on:
      - nginx
    networks:
      - totara

  pgsql15:
    image: postgres:15-alpine
    container_name: totara_pgsql15
    ports:
      - "5444:5432"
    environment:
      TZ: ${TIME_ZONE}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    command:
      postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./pgsql/my-postgres.conf:/etc/postgresql/postgresql.conf
      - pgsql15-data:/var/lib/postgresql/data
    depends_on:
      - nginx
    networks:
      - totara

volumes:
  pgsql93-data:
  pgsql96-data:
  pgsql10-data:
  pgsql11-data:
  pgsql12-data:
  pgsql13-data:
  pgsql14-data:
  pgsql15-data:
