services:
  php-7.3:
    image: totara/docker-dev-php73
    container_name: totara_php73
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.3
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-7.3-debug
    networks:
      - totara

  php-7.3-debug:
    image: totara/docker-dev-php73
    container_name: totara_php73_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.3-debug
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP}
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara73
      PHP_IDE_CONFIG: serverName=totara73
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-7.4:
    image: totara/docker-dev-php74
    container_name: totara_php74
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.4
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-7.4-debug
    networks:
      - totara

  php-7.4-debug:
    image: totara/docker-dev-php74
    container_name: totara_php74_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.4-debug
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP}
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara74
      PHP_IDE_CONFIG: serverName=totara74
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-8.0:
    image: totara/docker-dev-php80
    container_name: totara_php80
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.0
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-8.0-debug
    networks:
      - totara

  php-8.0-debug:
    image: totara/docker-dev-php80
    container_name: totara_php80_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.0-debug
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP}
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara80
      PHP_IDE_CONFIG: serverName=totara80
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-8.1:
    image: totara/docker-dev-php81
    container_name: totara_php81
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.1
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-8.1-debug
    networks:
      - totara

  php-8.1-debug:
    image: totara/docker-dev-php81
    container_name: totara_php81_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.1-debug
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP}
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara81
      PHP_IDE_CONFIG: serverName=totara81
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-8.2:
    image: totara/docker-dev-php82
    container_name: totara_php82
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.2
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-8.2-debug
    networks:
      - totara

  php-8.2-debug:
    image: totara/docker-dev-php82
    container_name: totara_php82_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.2-debug
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP}
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara82
      PHP_IDE_CONFIG: serverName=totara82
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-8.3:
    image: totara/docker-dev-php83
    container_name: totara_php83
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.3
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-8.3-debug
    networks:
      - totara

  php-8.3-debug:
    image: totara/docker-dev-php83
    container_name: totara_php83_debug
    restart: ${RESTART_POLICY:-no}
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.3-debug
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP}
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara83
      PHP_IDE_CONFIG: serverName=totara83
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-8.4:
    image: totara/docker-dev-php84
    container_name: totara_php84
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.4
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-8.4-debug
    networks:
      - totara

  php-8.4-debug:
    image: totara/docker-dev-php84
    container_name: totara_php84_debug
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.4-debug
      CRON_CONTAINER: ${CRON_CONTAINER:-none}
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: client_host=${HOST_IP}
      XDEBUG_MODE: debug
      XDEBUG_SESSION: totara84
      PHP_IDE_CONFIG: serverName=totara84
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: "true" # disables oh-my-zsh update message
      USE_ZSH_NERDFONT: ${USE_ZSH_NERDFONT:-0}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
      - ./php/includes:/var/www/totara/includes
      - coverage-report:/var/www/totara/coverage-report
      - bash-history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  # php-X.X: ...
  # php-X.X-debug: ...

  # When adding a new PHP container here, make sure you also:
  # - Add a build entry in compose/build.yml
  # - Add a mutagen sync entry in compose/sync.yml
  # - Add relevant network aliases in compose/nginx.yml and compose/apache.yml
  # - Add a CI build entry in .github/workflows/build-php.yml
  # - Update the max PHP version in .github/workflows/validate-config.yml
  # - Update README.md

volumes:
  totara-data:
  coverage-report:
  bash-history:
  zsh-history:
