version: "3.7"
services:

  php-5.3:
    image: totara/docker-dev-php53
    container_name: totara_php53
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-5.3
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-5.3-debug
    networks:
      - totara

  php-5.3-debug:
    image: totara/docker-dev-php53-debug
    container_name: totara_php53_debug
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-5.3-debug
      TZ: ${TIME_ZONE}
      HOST_IP: ${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara53
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-5.4:
    image: totara/docker-dev-php54
    container_name: totara_php54
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-5.4
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-5.4-debug
    networks:
      - totara

  php-5.4-debug:
    image: totara/docker-dev-php54-debug
    container_name: totara_php54_debug
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-5.4-debug
      TZ: ${TIME_ZONE}
      HOST_IP: ${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara54
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-5.4-cron:
    image: totara/docker-dev-php54-cron
    container_name: totara_php54_cron
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-5.5:
    image: totara/docker-dev-php55
    container_name: totara_php55
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-5.5
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-5.5-debug
    networks:
      - totara

  php-5.5-debug:
    image: totara/docker-dev-php55-debug
    container_name: totara_php55_debug
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-5.5-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara55
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-5.5-cron:
    image: totara/docker-dev-php55-cron
    container_name: totara_php55_cron
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-5.6:
    image: totara/docker-dev-php56
    container_name: totara_php56
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-5.6
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-5.6-debug
    networks:
      - totara

  php-5.6-debug:
    image: totara/docker-dev-php56-debug
    container_name: totara_php56_debug
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-5.6-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara56
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-5.6-cron:
    image: totara/docker-dev-php56-cron
    container_name: totara_php56_cron
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-7.0:
    image: totara/docker-dev-php70
    container_name: totara_php70
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.0
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-7.0-debug
    networks:
      - totara

  php-7.0-debug:
    image: totara/docker-dev-php70-debug
    container_name: totara_php70_debug
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.0-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara70
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-7.0-cron:
    image: totara/docker-dev-php70-cron
    container_name: totara_php70_cron
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-7.1:
    image: totara/docker-dev-php71
    container_name: totara_php71
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.1
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-7.1-debug
    networks:
      - totara

  php-7.1-debug:
    image: totara/docker-dev-php71-debug
    container_name: totara_php71_debug
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.1-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara71
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-7.1-cron:
    image: totara/docker-dev-php71-cron
    container_name: totara_php71_cron
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-7.2:
    image: totara/docker-dev-php72
    container_name: totara_php72
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.2
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-7.2-debug
    networks:
      - totara

  php-7.2-debug:
    image: totara/docker-dev-php72-debug
    container_name: totara_php72_debug
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.2-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara72
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-7.2-cron:
    image: totara/docker-dev-php72-cron
    container_name: totara_php72_cron
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-7.3:
    image: totara/docker-dev-php73
    container_name: totara_php73
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.3
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-7.3-debug
    networks:
      - totara

  php-7.3-debug:
    image: totara/docker-dev-php73-debug
    container_name: totara_php73_debug
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.3-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara73
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-7.3-cron:
    image: totara/docker-dev-php73-cron
    container_name: totara_php73_cron
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-7.4:
    image: totara/docker-dev-php74
    container_name: totara_php74
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.4
      TZ: ${TIME_ZONE}
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    depends_on:
      - php-7.4-debug
    networks:
      - totara

  php-7.4-debug:
    image: totara/docker-dev-php74-debug
    container_name: totara_php74_debug
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-7.4-debug
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=totara74
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-7.4-cron:
    image: totara/docker-dev-php74-cron
    container_name: totara_php74_cron
    environment:
      TZ: ${TIME_ZONE}
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-8.0:
    image: totara/docker-dev-php80
    container_name: totara_php80
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.0
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-8.0-cron:
    image: totara/docker-dev-php80-cron
    container_name: totara_php80_cron
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
    networks:
      - totara

  php-8.1:
    image: totara/docker-dev-php81
    container_name: totara_php81
    working_dir: ${REMOTE_SRC}
    environment:
      CONTAINERNAME: php-8.1
      HIST_FILE: /root/.bash_history
      DISABLE_AUTO_UPDATE: true # disables oh-my-zsh update message
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - $HOME/.bash_history:/root/.bash_history
      - zsh-history:/root/.zsh_history
      - ./shell:/root/custom_shell
    networks:
      - totara

  php-8.1-cron:
    image: totara/docker-dev-php81-cron
    container_name: totara_php81_cron
    volumes:
      - ${LOCAL_SRC}:${REMOTE_SRC}
      - totara-data:${REMOTE_DATA}
      - ./cron.d:/etc/cron.d
    networks:
      - totara

volumes:
  totara-data:
  zsh-history:
