services:

  selenium-hub:
    image: selenium/hub:4.28.1
    container_name: totara_seleniumhub
    restart: ${RESTART_POLICY:-no}
    ports:
      - "4444:4444"
    networks:
      - totara
    environment:
      - TZ=${TIME_ZONE}
      - GRID_MAX_SESSION=8
      - GRID_TIMEOUT=7200
      - GRID_CLEAN_UP_CYCLE=120000
    depends_on:
      - selenium-chrome

  selenium-chrome:
    image: selenium/node-chromium:132.0
    restart: ${RESTART_POLICY:-no}
    environment:
      - TZ=${TIME_ZONE}
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2gb
    networks:
      - totara

  selenium-chrome-debug:
    image: selenium/standalone-chromium:132.0
    container_name: totara_chrome_standalone_debug
    restart: ${RESTART_POLICY:-no}
    ports:
      - "5902:5900"
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - totara