services:

  selenium-hub:
    image: selenium/hub:4.5.3
    container_name: totara_seleniumhub
    restart: ${RESTART_POLICY:-no}
    ports:
      - "4444:4444"
    networks:
      - totara
    environment:
      - TZ=${TIME_ZONE}
      - GRID_MAX_SESSION=8
      - GRID_TIMEOUT=7200
      - GRID_CLEAN_UP_CYCLE=120000
    depends_on:
      - selenium-chrome

  selenium-chrome:
    image: selenium/node-chrome:106.0
    restart: ${RESTART_POLICY:-no}
    environment:
      - TZ=${TIME_ZONE}
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2gb
    networks:
      - totara

  selenium-chrome-debug:
    image: selenium/standalone-chromium:126.0 # For Totara 19+
    container_name: totara_chrome_standalone_debug
    restart: ${RESTART_POLICY:-no}
    ports:
      - "5902:5900"
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - totara

  selenium-chrome-debug-legacy:
    image: selenium/standalone-chrome:102.0 # For Totara 18 and older
    container_name: totara_chrome_standalone_debug_legacy
    restart: ${RESTART_POLICY:-no}
    ports:
      - "5903:5900"
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - totara

  selenium-chrome-debug-latest:
    image: selenium/standalone-chromium:latest # For Totara 19+
    container_name: totara_chrome_standalone_debug_latest
    restart: ${RESTART_POLICY:-no}
    ports:
      - "5904:5900"
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - totara

  selenium-edge-debug:
    image: selenium/standalone-edge:latest # For Totara 19+
    container_name: totara_edge_standalone_debug
    restart: ${RESTART_POLICY:-no}
    ports:
      - "5905:5900"
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - totara

  selenium-firefox-debug:
    image: selenium/standalone-firefox:latest # For Totara 19+
    container_name: totara_firefox_standalone_debug
    restart: ${RESTART_POLICY:-no}
    ports:
      - "5906:5900"
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - totara