version: "3.7"
services:

  selenium-hub:
    image: selenium/hub:3.13
    container_name: totara_seleniumhub
    ports:
      - "4444:4444"
    networks:
      - totara
    environment:
      - GRID_MAX_SESSION=8
      - GRID_TIMEOUT=7200
      - GRID_CLEAN_UP_CYCLE=120000
    depends_on:
      - selenium-chrome

  selenium-chrome:
    image: selenium/node-chrome:3.13
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_INSTANCES=8
      - NODE_MAX_SESSION=8
    networks:
      - totara

  selenium-chrome-debug:
    image: selenium/standalone-chrome-debug:3.13
    container_name: totara_chrome_standalone_debug
    ports:
      - "5901:5900"
    networks:
      - totara

  selenium-chrome-standalone:
    image: selenium/standalone-chrome:3.13
    container_name: totara_chrome_standalone
    ports:
      - "4445:4444"
    networks:
      - totara
