version: "3.7"
services:

  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: totara_seleniumhub
    ports:
      - "4444:4444"
    networks:
      - totara
    environment:
      - TZ=${TIME_ZONE}
      - GRID_MAX_SESSION=8
      - GRID_TIMEOUT=7200
      - GRID_CLEAN_UP_CYCLE=120000
    depends_on:
      - selenium-chrome

  selenium-chrome:
    image: selenium/node-chrome:3.141.59
    environment:
      - TZ=${TIME_ZONE}
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - totara

  selenium-chrome-debug:
    image: selenium/standalone-chrome-debug:3.141.59
    container_name: totara_chrome_standalone_debug
    ports:
      - "5902:5900"
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - totara

  selenium-chrome-standalone:
    image: selenium/standalone-chrome:3.141.59
    container_name: totara_chrome_standalone
    ports:
      - "4445:4444"
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - totara
