on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      multiarch:
        required: false
        type: boolean
        default: true

jobs:
  build-php-image:
    name: Build PHP ${{ inputs.version }} image
    uses: ./.github/workflows/build-image.yml
    with:
      image: php${{ inputs.version }}
      context: ./php/php${{ inputs.version }}
      multiarch: ${{ inputs.multiarch }}
    secrets: inherit

  build-php-debug-image:
    name: Build PHP ${{ inputs.version }} debug image
    needs: build-php-image
    uses: ./.github/workflows/build-image.yml
    with:
      image: php${{ inputs.version }}-debug
      context: ./php/php${{ inputs.version }}-debug
      multiarch: ${{ inputs.multiarch }}
    secrets: inherit

  build-php-cron-image:
    name: Build cron image
    needs: build-php-image
    uses: ./.github/workflows/build-image.yml
    with:
      image: php${{ inputs.version }}-cron
      context: ./php/php${{ inputs.version }}-cron
      multiarch: ${{ inputs.multiarch }}
    secrets: inherit
