name: Trivy Image Vulnerability Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 0' # Run every Monday at 6am NZST

permissions:
  contents: read

jobs:
  scan-image:
    name: Scan ${{ matrix.image }} image for vulnerabilities
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - image: mssql2017
          - image: mssql2019
          - image: mssql2022
          - image: php73
          - image: php74
          - image: php80
          - image: php81
          - image: php82
          - image: php83
          - image: php84
          - image: php85
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Pull image to scan
        run: docker pull ghcr.io/totara/docker-dev-${{ matrix.image }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ghcr.io/totara/docker-dev-${{ matrix.image }}
          format: 'sarif'
          output: trivy-results-${{ matrix.image }}-image.sarif
          severity: 'CRITICAL,HIGH'
          limit-severities-for-sarif: true
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@b96794f015dfd88f77b49b1c93e0fa7110f94c63 # v4.38.0
        with:
          sarif_file: trivy-results-${{ matrix.image }}-image.sarif
